const events = [
    {
      event_name: "Round-robin tournament",
      event_date: new Date(2024, 3, 5, 9, 0),
      event_duration: 6,
      event_description: "A friendly tennis tournament where players compete in a round-robin format.",
      organizing_group: "Ace Tennis Club",
      event_slots: 10,
      event_registration_fees: 20,
      event_format: "Tournament",
      member_skill_level: "All",
      event_rules: "Matches consist of one set, tiebreak at 6-6. Winners progress to next round.",
      event_equipment_needed: "Tennis racket and proper attire; tennis balls will be provided",
    },
    {
      event_name: "Tennis clinic for beginners",
      event_date: new Date(2024, 3, 12, 10, 0),
      event_duration: 2,
      event_description: "An introductory tennis clinic designed for beginners to learn basic techniques.",
      organizing_group: "Ace Tennis Club",
      event_slots: 10,
      event_registration_fees: 15,
      event_format: "Instructional",
      member_skill_level: "Beginners",
      event_rules: "Participants will receive instruction on grips, strokes, and footwork.",
      event_equipment_needed: "Tennis racket, comfortable clothing, tennis shoes; tennis balls will be provided",
    },
    {
      event_name: "Advanced doubles strategy workshop",
      event_date: new Date(2024, 3, 17, 13, 0),
      event_duration: 3,
      event_description: "A workshop focusing on advanced strategies and tactics for doubles tennis.",
      organizing_group: "Smash Tennis Association",
      event_slots: 10,
      event_registration_fees: 20,
      event_format: "Instructional",
      member_skill_level: "Intermediate+",
      event_rules: "In-depth analysis of positioning, communication, and shot selection in doubles play.",
      event_equipment_needed: "Tennis racket, tennis shoes, notepad",
    },
    {
      event_name: "Fast-serve competition",
      event_date: new Date(2024, 3, 8, 11, 0),
      event_duration: 2,
      event_description: "A competition to test the speed and accuracy of players' serves.",
      organizing_group: "Net Rush Tennis Group",
      event_slots: 10,
      event_registration_fees: 6,
      event_format: "Tournament",
      member_skill_level: "Pro",
      event_rules: "Players serve from baseline, aiming for accuracy and speed. Radar gun used for measurement.",
      event_equipment_needed: "Tennis racket, tennis balls, water bottle",
    },
    {
      event_name: "Tennis footwork clinic",
      event_date: new Date(2024, 3, 15, 15, 0),
      event_duration: 2,
      event_description: "A clinic focusing on improving footwork and movement on the tennis court.",
      organizing_group: "Net Rush Tennis Group",
      event_slots: 10,
      event_registration_fees: 15,
      event_format: "Instructional",
      member_skill_level: "Pro",
      event_rules: "Drills and exercises to enhance agility, speed, and court coverage.",
      event_equipment_needed: "Tennis racket, tennis shoes, comfortable clothing",
    },
    {
      event_name: "Womens Singles Play",
      event_date: new Date(2024, 3, 6, 10, 0),
      event_duration: 4,
      event_description: "An exclusive event for women singles players to enjoy competitive matches.",
      organizing_group: "Volley Ladies",
      event_slots: 8,
      event_registration_fees: 0,
      event_format: "Instructional",
      member_skill_level: "All Levels",
      event_rules: "Matches consist of one set, tiebreak at 6-6. Winners progress to next round.",
      event_equipment_needed: "Tennis racket, tennis balls, appropriate attire",
    },
    {
      event_name: "Baseline Battle Play",
      event_date: new Date(2024, 3, 7, 14, 0),
      event_duration: 3,
      event_description: "A high-energy event focusing on intense baseline play and strategy.",
      organizing_group: "Baseline Brawlers",
      event_slots: 15,
      event_registration_fees: 20,
      event_format: "Tournament",
      member_skill_level: "Pro",
      event_rules: "Players engage in fast-paced rallies, aiming to dominate from the baseline.",
      event_equipment_needed: "Tennis racket, tennis balls, water bottle",
    },
    ]

    module.exports = events
