const groups = [
    {group_name: "Ace Tennis Club",
    group_description: "A community of tennis enthusiasts dedicated to improving their game and enjoying friendly matches.",
    group_type: "All levels, 18+",
    group_membership_criteria: "Open to all tennis players regardless of skill level and over 18 years old",
    group_courts: ["Central Park Tennis Courts", "Riverside Park Tennis Courts"],
    group_admin: "Tina",
    group_member_directory: ["Amy", "Ben", "Chloe"],
    group_upcoming_events: ["Round-robin tournament", "Tennis clinic for beginners"],
    group_rules: "Respect opponents and play with sportsmanship.",
    announcements: ["Reminder: New Events posted; remeber to register for the events"],
    zip_code: 75010,
    },
    {group_name: "Smash Tennis Association",
    group_description: "A passionate community of tennis lovers who enjoy competitive matches and camaraderie.",
    group_type: "Intermediate level+, 18+",
    group_membership_criteria: "Open to all tennis players of intermediate skill and above and over 18 years old",
    group_courts: ["City Hall Tennis Courts", "Central Park Tennis Courts"],
    group_admin: "Anna",
    group_member_directory: ["Daniel", "Eva", "Fiona", "Claire"],
    group_upcoming_events: ["Singles ladder tournament", "Advanced doubles strategy workshop"],
    group_rules: "Compete with integrity and respect fellow players.",
    announcements: ["Advanced doubles strategy workshop scheduled for next week. Remember to check out the events for more details"],
    zip_code: 75010,
    },
    {group_name: "Net Rush Tennis Group",
    group_description: "A dynamic tennis community focused on fast-paced matches and skill development.",
    group_type: "Pro-level, Teens/Adult",
    group_membership_criteria: "Open to pro-level tennis players with a competitive spirit and a desire to improve.",
    group_courts: ["Riverside Park Tennis Courts", "City Hall Tennis Courts"],
    group_admin: "Bill",
    group_member_directory: ["George", "Hannah", "Ian", "Phil"],
    group_upcoming_events: ["Fast-serve competition", "Tennis footwork clinic"],
    group_rules: "Play aggressively but with respect for opponents.",
    announcements: ["Fast-serve competition registration now open.Check out events details for link to registration"],
    zip_code: 75010,
    },
    {group_name: "Volley Ladies",
    group_description: "A space for women in tennis to develop their skills and build a community",
    group_type: "All Levels, Teens/Adult",
    group_membership_criteria: "Open to all levels of tennis women players.",
    group_courts: ["Community Center Tennis Courts", "Pine Grove Park Tennis Courts"],
    group_admin: "Anna",
    group_member_directory: ["Tina", "Hannah", "Tania", "Sonia", "Karen"],
    group_upcoming_events: ["Womens Singles Play"],
    group_rules: "Have fun and learn",
    announcements: ["Registration for the Womens Singles Play is now open"],
    zip_code: 75035,
    },
    {group_name: "Basseline Brawler",
    group_description: "An energetic tennis group dedicated to dominating matches with powerful groundstrokes and strategic play.",
    group_type: "Pro-Level, 18+",
    group_membership_criteria: "Open to pro-level and for ages over 20+",
    group_courts: ["Beachside Tennis Courts", "Downtown Tennis Courts"],
    group_admin: "George",
    group_member_directory: ["Jack", "Katie", "Liam", "Jamie"],
    group_upcoming_events: ["Baseline battle Play"],
    group_rules: "Hit hard, move fast, and never give up.",
    announcements: ["Baseline battle tournament registration closing soon."],
    zip_code: 75035,
    },
    ]

    module.exports = groups